export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ORDERS_FAIL';

// Filtering Actions
export const INPUT_ONCHANGED_HANDLER = 'INPUT_ONCHANGED_HANDLER';
export const CATEGORY_FILTER_HANDLER = 'CATEGORY_FILTER_HANDLER';
export const CATEGORY_RESETTING_HANDLER = 'CATEGORY_RESETTING_HANDLER';

export const TOGGLE_UPDATING = 'TOGGLE_UPDATING';
export const TOGGLE_UPDATING_FALSE = 'TOGGLE_UPDATING_FALSE';
export const UPDATE_ITEM_START = 'UPDATE_ITEM_START';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';
export const DELETION_ITEM_START = 'DELETION_ITEM_START';
export const DELETE_ITEM_START = 'DELETE_ITEM_START';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
export const DELETE_ITEM_CANCEL = 'DELETE_ITEM_CANCEL';

//Authentication Actions:

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const ERROR_AUTHENTICATION_CLEARING = 'ERROR_AUTHENTICATION_CLEARING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CREATING_ACCOUNT_STATUS_TOGGLE = 'CREATING_ACCOUNT_STATUS_TOGGLE';
export const PASSWORD_MATCH_CONFIRMATION = 'PASSWORD_MATCH_CONFIRMATION';

// Update or Delete ToolTip:

export const REQUESTED_TOOL_TIP = 'REQUESTED_TOOL_TIP';
export const CLOSE_TOOL_TIP = 'CLOSE_TOOL_TIP';
export const ITEM_ID_FOR_TOOL_TIP = 'ITEM_ID_FOR_TOOL_TIP';
