export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ORDERS_FAIL';
export const INPUT_ONCHANGED_HANDLER = 'INPUT_ONCHANGED_HANDLER';
export const CATEGORY_FILTER_HANDLER = 'CATEGORY_FILTER_HANDLER';
export const TOGGLE_UPDATING = 'TOGGLE_UPDATING';
export const TOGGLE_UPDATING_FALSE = 'TOGGLE_UPDATING_FALSE';
